spring:
  datasource:
      primary:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/second_kill?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
        username: root
        password: root
      slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/second_kill?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
        username: root
        password: root
  redis:
    host: localhost
    port: 6379
    password: 123456

logging:
  file:
    path: E:/logs/hello/
    max-history: 30
    max-size: 20MB
