spring:
  datasource:
    primary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/scaffold?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
      username: root
      password: root
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/scaffold?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
      username: root
      password: root
  redis:
    host: localhost
    port: 6379
    password: "codechen"
  quartz:
    # 定时任务的数据保存到数据库中
    job-store-type: jdbc
    jdbc:
      # embedded：默认
      # always：启动的时候初始化表，只在第一次启动的时候用它来自动创建表，然后改回embedded即可，不然数据每次都会被清空
      # never：启动的时候不初始化表，也不知道和embedded有什么不同
      initialize-schema: embedded

logging:
  file:
    path: E:/logs/scaffold/
    max-history: 30
    max-size: 20MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 滑块验证码配置， 详细请看 cloud.tianai.captcha.autoconfiguration.ImageCaptchaProperties 类
captcha:
  # 如果项目中使用到了redis，滑块验证码会自动把验证码数据存到redis中， 这里配置redis的key的前缀,默认是captcha:slider
  prefix: captcha
  # 验证码过期时间，默认是2分钟,单位毫秒， 可以根据自身业务进行调整
  expire:
    # 默认缓存时间 2分钟
    default: 30000
    # 针对 点选验证码 过期时间设置为 2分钟， 因为点选验证码验证比较慢，把过期时间调整大一些
    WORD_IMAGE_CLICK: 20000
  # 使用加载系统自带的资源， 默认是 false
  init-default-resource: false
  cache:
    # 缓存控制， 默认为false不开启
    enabled: false
    # 验证码会提前缓存一些生成好的验证数据， 默认是20
    cacheSize: 20
    # 缓存拉取失败后等待时间 默认是 5秒钟
    wait-time: 5000
    # 缓存检查间隔 默认是2秒钟
    period: 2000
  secondary:
    # 二次验证， 默认false 不开启
    enabled: false
    # 二次验证过期时间， 默认 2分钟
    expire: 120000
    # 二次验证缓存key前缀，默认是 captcha:secondary
    keyPrefix: "captcha:secondary"

codechen:
  auth:
    token-secret: "拳打南山敬老院，脚踢北海幼儿园"
    token-expired-time: 3600000
    exclude-urls: "/doc.html,/webjars/*,/swagger-resources,/v2/api-docs,/login/*"
  generator:
    package-name: com.codechen.scaffold.admin
#    ignore-table-prefix: true
#    table-prefix: mnt
    author: Java陈序员
    enable-swagger: false
    base-entity: com.codechen.scaffold.framework.domain.AbstractEntity
    common-result: com.codechen.scaffold.common.domain.Result
    ignore-column: id,created_time,update_time,deleted,version
#    entity-suffix: ''
#    mapper-suffix: Dao
#    create-time: "2024-12-12 15:17:42"
