spring:
  application:
    name: dev-scaffold
  profiles:
    active: @environment@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 8080

logging:

  file:
    path: E:/logs/hello/
    max-size: 20MB
    max-history: 30